Repository cesium/hydrogen, pull requests merged in 2025-03, with the labels that each got.

#101 feat: `/about/partners` partner list
  bun.lockb
  public/images/partners/100montaditos.png
  public/images/partners/apecoffee.webp
  public/images/partners/bragapizzariakebab.png
  public/images/partners/cafedoluis.jpg
  public/images/partners/drawstep.avif
  public/images/partners/escoladeconducaoum.png
  public/images/partners/magicpin.png
  public/images/partners/nuguel.png
  public/images/partners/osfarias.jpg
  public/images/partners/pausautil.png
  public/images/partners/sabordafruta.png
  public/images/partners/thetraditionalgreatpizza.png
  src/app/[lang]/partners/page.tsx
  src/internationalization/dictionaries/en.json
  src/internationalization/dictionaries/pt.json
Labels: pending changes

#110 feat: /about page "O que é o CeSIUM?" section
  package-lock.json
  public/images/sei24-25.jpg
  public/images/uMinho1.jpg
  public/images/uMinho2.jpg
  public/images/workshop.jpg
  src/app/[lang]/about/departments/page.tsx
  src/app/[lang]/about/page.tsx
  src/app/[lang]/globals.css
  src/internationalization/dictionaries/en.json
  src/internationalization/dictionaries/pt.json
  src/lib/utils.ts
Labels: pending changes

#97 feat: `/about` page Departments section
  src/app/[lang]/about/departments/page.tsx
  src/app/[lang]/about/page.tsx
  src/app/[lang]/layout.tsx
  src/components/about-section-layout.tsx
  src/components/about-section.tsx
  src/components/department-card.tsx
  src/components/departments-list.tsx
  src/components/navbar.tsx
  src/internationalization/dictionaries/en.json
  src/internationalization/dictionaries/pt.json
  tailwind.config.ts
Labels: p: high 🔥

#70 feat: events page
  bun.lockb
  package.json
  src/app/[lang]/about/become-a-collaborator/layout.tsx
  src/app/[lang]/about/become-a-member/layout.tsx
  src/app/[lang]/about/departments/layout.tsx
  src/app/[lang]/about/layout.tsx
  src/app/[lang]/about/team/layout.tsx
  src/app/[lang]/events/layout.tsx
  src/app/[lang]/events/page.tsx
  src/app/[lang]/layout.tsx
  src/app/[lang]/page.tsx
  src/app/[lang]/partners/layout.tsx
  src/app/[lang]/projects/layout.tsx
  src/components/calendar.tsx
  src/components/event-card.tsx
  src/components/event-list-skeleton.tsx
  src/components/event-list.tsx
  src/components/event-skeleton.tsx
  src/components/event-tooltip.tsx
  src/components/link.tsx
  src/components/loading-spinner.tsx
  src/components/navbar.tsx
  src/contexts/dictionary-provider.tsx
  src/internationalization/dictionaries.ts
  src/internationalization/dictionaries/en.json
  src/internationalization/dictionaries/pt.json
  src/lib/api/getEvents.ts
  src/lib/locale.ts
  src/lib/types.ts
  src/lib/utils.ts
  src/middleware.ts
Labels: p: critical 🚨

#130 feat: /about page Hero
  src/app/[lang]/about/page.tsx
  src/app/[lang]/globals.css
  src/components/carousel.tsx
  src/internationalization/dictionaries/en.json
  src/internationalization/dictionaries/pt.json
Labels: pending changes

#155 feat: landing Hero
  public/vectors/hero-mobile.svg
  public/vectors/hero.svg
  src/app/[lang]/layout.tsx
  src/app/[lang]/page.tsx
  src/components/about-section-layout.tsx
  src/components/body.tsx
  src/components/navbar.tsx
  src/contexts/scrollstate-provider.tsx
  src/internationalization/dictionaries/en.json
  src/internationalization/dictionaries/pt.json
Labels: p: high 🔥

#153 feat: call to subscribe component
  src/app/[lang]/about/become-a-collaborator/page.tsx
  src/app/[lang]/about/become-a-member/page.tsx
  src/components/call-subscribe.tsx
  src/internationalization/dictionaries/en.json
  src/internationalization/dictionaries/pt.json
Labels: enhancement

#160 fix: relative image path causing failures
  src/app/[lang]/page.tsx
Labels: bug

#177 chore: improve AppLink & Button and use them globally
  src/app/[lang]/about/become-a-member/page.tsx
  src/app/[lang]/about/page.tsx
  src/app/[lang]/events/page.tsx
  src/components/about-section-layout.tsx
  src/components/button.tsx
  src/components/call-subscribe.tsx
  src/components/department-card.tsx
  src/components/link.tsx
  src/components/navbar.tsx
  src/components/partner-card.tsx
  src/components/project-card.tsx
  src/components/promotional-card.tsx
  src/components/shortcut-panes.tsx
  src/contexts/scrollstate-provider.tsx
Labels: enhancement

#182 fix: become a member hero
  src/app/[lang]/about/become-a-member/page.tsx
Labels: bug

#164 refactor: use CSS classes for layout paddings instead of TS variables
  src/app/[lang]/[...404]/page.tsx
  src/app/[lang]/about/become-a-collaborator/page.tsx
  src/app/[lang]/about/become-a-member/page.tsx
  src/app/[lang]/about/page.tsx
  src/app/[lang]/departments/page.tsx
  src/app/[lang]/events/page.tsx
  src/app/[lang]/globals.css
  src/app/[lang]/page.tsx
  src/app/[lang]/partners/page.tsx
  src/app/[lang]/team/page.tsx
  src/components/about-section.tsx
  src/components/event-tooltip.tsx
  src/components/footer.tsx
  src/components/navbar.tsx
  src/components/project-card.tsx
  src/components/scrollable-highlight.tsx
  src/lib/styling.ts
  tailwind.config.ts
Labels: enhancement
